import type { NexusResourceTuple } from "./types";

export const aiResources = {
  "ml_youtube": [
    "Machine learning with scikit-learn",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=scikit-learn+machine+learning+full+course+2026",
    "Watch a recent end-to-end scikit-learn course before implementing feature, evaluation, and serving pipelines.",
  ],
  "google_ml": [
    "Machine Learning Crash Course",
    "Course",
    "Google",
    "https://developers.google.com/machine-learning/crash-course/",
    "Video-backed lessons, visual explanations, quizzes, and exercises for practical ML foundations.",
  ],
  "sklearn_mooc": [
    "scikit-learn MOOC",
    "Course",
    "Inria",
    "https://inria.github.io/scikit-learn-mooc/",
    "Free notebook-based course on preprocessing, pipelines, model selection, evaluation, and interpretation.",
  ],
  "model_cards": [
    "Model Cards",
    "Read",
    "Google Research",
    "https://modelcards.withgoogle.com/about",
    "Document intended use, evaluation, limitations, ethical considerations, and model version details.",
  ],
  "shap": [
    "SHAP documentation",
    "Reference",
    "SHAP",
    "https://shap.readthedocs.io/en/latest/",
    "Explain model outputs, choose explainers, produce plots, and interpret feature contributions.",
  ],
  "mlflow": [
    "MLflow getting started",
    "Course",
    "MLflow",
    "https://mlflow.org/docs/latest/ml/getting-started/",
    "Experiment tracking, model packaging, registries, evaluation, aliases, and deployment workflows.",
  ],
  "mlflow_youtube": [
    "MLflow experiment tracking and registry",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=MLflow+experiment+tracking+model+registry+full+tutorial+2026",
    "Watch a current MLflow walkthrough, then implement the same lifecycle in the Nexus registry.",
  ],
  "mlflow_registry": [
    "MLflow Model Registry",
    "Reference",
    "MLflow",
    "https://mlflow.org/docs/latest/ml/model-registry/",
    "Model versions, aliases, tags, promotion, lineage, rollback, and deployment integration.",
  ],
  "evidently": [
    "Evidently documentation",
    "Reference",
    "Evidently AI",
    "https://docs.evidentlyai.com/",
    "Data and prediction drift, test suites, reports, monitoring, and production evaluation.",
  ],
  "rag_youtube": [
    "Production RAG course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=production+RAG+course+pgvector+citations+2026",
    "Watch a recent end-to-end RAG course covering ingestion, embeddings, retrieval, citations, evaluation, and deployment.",
  ],
  "hf_llm": [
    "Hugging Face LLM Course",
    "Course",
    "Hugging Face",
    "https://huggingface.co/learn/llm-course/chapter1/1",
    "Transformers, tokenizers, datasets, embeddings, fine-tuning, demos, and practical NLP workflows.",
  ],
  "langchain_rag": [
    "Build a RAG application",
    "Read",
    "LangChain",
    "https://docs.langchain.com/oss/python/langchain/rag",
    "Official retrieval, indexing, prompting, streaming, citations, and production patterns.",
  ],
  "pgvector": [
    "pgvector documentation",
    "Reference",
    "pgvector",
    "https://github.com/pgvector/pgvector",
    "Vector types, distance functions, HNSW/IVFFlat indexes, filtering, and hybrid search in PostgreSQL.",
  ],
  "mcp_course": [
    "Model Context Protocol Course",
    "Course",
    "Hugging Face and Anthropic",
    "https://huggingface.co/learn/mcp-course/en/unit0/introduction",
    "Free structured course covering MCP architecture, SDKs, tools, servers, clients, and deployed projects.",
  ],
  "mcp_docs": [
    "Model Context Protocol documentation",
    "Reference",
    "Model Context Protocol",
    "https://modelcontextprotocol.io/docs/getting-started/intro",
    "Current protocol concepts, transports, tools, resources, prompts, SDKs, and security guidance.",
  ],
  "ragas": [
    "Ragas documentation",
    "Reference",
    "Ragas",
    "https://docs.ragas.io/en/stable/",
    "RAG test-set creation, retrieval metrics, response evaluation, experiments, and quality monitoring.",
  ],
  "openai_evals": [
    "OpenAI Cookbook: evaluations",
    "Read",
    "OpenAI",
    "https://cookbook.openai.com/topic/evals",
    "Practical evaluation design, datasets, graders, model comparisons, and failure analysis.",
  ],
  "pymupdf": [
    "PyMuPDF documentation",
    "Reference",
    "PyMuPDF",
    "https://pymupdf.readthedocs.io/en/latest/",
    "PDF text extraction, page rendering, images, coordinates, OCR integration, and document processing.",
  ],
  "ai_safety_youtube": [
    "LLM security and prompt injection",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=OWASP+LLM+Top+10+prompt+injection+security+2026",
    "Watch current OWASP GenAI and practitioner sessions before implementing the safety gateway and red-team harness.",
  ],
  "owasp_llm": [
    "OWASP Top 10 for LLM Applications",
    "Read",
    "OWASP GenAI Security Project",
    "https://genai.owasp.org/llm-top-10/",
    "Prompt injection, sensitive data, supply chain, excessive agency, insecure output, and system prompt risks.",
  ],
  "nist_ai": [
    "NIST AI RMF Playbook",
    "Read",
    "NIST",
    "https://airc.nist.gov/AI_RMF_Knowledge_Base/Playbook",
    "Practical actions for governing, mapping, measuring, and managing AI risk.",
  ],
  "presidio": [
    "Microsoft Presidio documentation",
    "Reference",
    "Microsoft",
    "https://microsoft.github.io/presidio/",
    "PII detection, anonymization, custom recognizers, structured/unstructured data, and deployment.",
  ],
  "pyrit": [
    "PyRIT documentation",
    "Reference",
    "Microsoft",
    "https://azure.github.io/PyRIT/",
    "Automated generative-AI red teaming, attack orchestration, scoring, datasets, and reporting.",
  ],
  "langgraph_youtube": [
    "LangGraph agents course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=LangGraph+multi-agent+human+in+the+loop+full+course+2026",
    "Watch current official and community walkthroughs of supervisors, tools, approval gates, and durable execution.",
  ],
  "langgraph": [
    "LangGraph Academy",
    "Course",
    "LangChain",
    "https://academy.langchain.com/",
    "Structured courses on graph state, tools, memory, human-in-the-loop, deployment, and observability.",
  ],
  "langgraph_docs": [
    "LangGraph documentation",
    "Reference",
    "LangChain",
    "https://docs.langchain.com/oss/python/langgraph/overview",
    "State graphs, persistence, interrupts, subgraphs, streaming, deployment, and production agent patterns.",
  ],
  "langsmith": [
    "LangSmith observability",
    "Reference",
    "LangChain",
    "https://docs.smith.langchain.com/",
    "Tracing, datasets, evaluations, feedback, dashboards, and debugging for agents and LLM applications.",
  ],
} as const satisfies Record<string, NexusResourceTuple>;
