import type { NexusResourceTuple } from "./types";

export const cloudSecurityResources = {
  "aws_skill": [
    "AWS Skill Builder",
    "Course",
    "Amazon Web Services",
    "https://skillbuilder.aws/",
    "Official training for cloud foundations, architecture, security, and certification preparation.",
  ],
  "aws_youtube": [
    "AWS Solutions Architect learning path",
    "Watch",
    "AWS / YouTube curated search",
    "https://www.youtube.com/results?search_query=AWS+Solutions+Architect+Associate+SAA-C03+full+course+2026",
    "Watch current architecture and SAA-focused lessons from AWS and reputable instructors.",
  ],
  "aws_well": [
    "AWS Well-Architected Framework",
    "Read",
    "Amazon Web Services",
    "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html",
    "Use the six pillars to review architecture, security, reliability, operations, performance, cost, and sustainability.",
  ],
  "aws_vpc": [
    "Amazon VPC documentation",
    "Reference",
    "Amazon Web Services",
    "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html",
    "Subnets, routing, NAT, internet gateways, network ACLs, security groups, and flow logs.",
  ],
  "aws_iam": [
    "IAM best practices",
    "Reference",
    "Amazon Web Services",
    "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
    "Least privilege, temporary credentials, MFA, policy analysis, and permission boundaries.",
  ],
  "aws_rds": [
    "Amazon RDS for PostgreSQL",
    "Reference",
    "Amazon Web Services",
    "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html",
    "Private database deployment, backups, monitoring, parameter groups, security, and migration.",
  ],
  "aws_exam": [
    "AWS Solutions Architect Associate exam guide",
    "Read",
    "Amazon Web Services",
    "https://docs.aws.amazon.com/aws-certification/latest/solutions-architect-associate-03.html",
    "Current SAA-C03 scope, domains, task statements, and exam preparation guidance.",
  ],
  "security_plus": [
    "CompTIA Security+",
    "Course",
    "CompTIA",
    "https://www.comptia.org/certifications/security",
    "Official certification overview, objectives, exam information, and training options.",
  ],
  "terraform": [
    "Terraform tutorials",
    "Course",
    "HashiCorp",
    "https://developer.hashicorp.com/terraform/tutorials",
    "Official step-by-step learning for configuration, state, modules, workflows, testing, and cloud deployment.",
  ],
  "terraform_youtube": [
    "Terraform full course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=HashiCorp+Terraform+full+course+AWS+2026",
    "Watch a current Terraform course, then use HashiCorp’s tutorials as the source of truth.",
  ],
  "terraform_aws": [
    "Terraform AWS provider",
    "Reference",
    "HashiCorp",
    "https://registry.terraform.io/providers/hashicorp/aws/latest/docs",
    "Authoritative resource and data-source reference for building AWS modules.",
  ],
  "terraform_security": [
    "Terraform security guidance",
    "Reference",
    "OWASP",
    "https://owasp.org/www-project-devsecops-guideline/latest/02c-Terraform",
    "Security considerations for state, secrets, providers, modules, scanning, and CI/CD.",
  ],
  "k8s_basics": [
    "Kubernetes Basics",
    "Course",
    "Kubernetes",
    "https://kubernetes.io/docs/tutorials/kubernetes-basics/",
    "Official interactive path through deployments, services, scaling, updates, and debugging.",
  ],
  "k8s_youtube": [
    "Kubernetes full course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=Kubernetes+full+course+2026+TechWorld+with+Nana",
    "Use a current beginner-to-production course to visualize cluster objects before writing manifests.",
  ],
  "k8s_rbac": [
    "Kubernetes RBAC",
    "Reference",
    "Kubernetes",
    "https://kubernetes.io/docs/reference/access-authn-authz/rbac/",
    "Roles, ClusterRoles, bindings, service accounts, privilege escalation prevention, and good practices.",
  ],
  "k8s_network": [
    "Network Policies",
    "Reference",
    "Kubernetes",
    "https://kubernetes.io/docs/concepts/services-networking/network-policies/",
    "Default-deny and allow-list network controls for namespaces, pods, and ports.",
  ],
  "k8s_pod": [
    "Pod Security Standards",
    "Reference",
    "Kubernetes",
    "https://kubernetes.io/docs/concepts/security/pod-security-standards/",
    "Privileged, baseline, and restricted controls for workload hardening.",
  ],
  "prometheus": [
    "Prometheus getting started",
    "Reference",
    "Prometheus",
    "https://prometheus.io/docs/prometheus/latest/getting_started/",
    "Metrics instrumentation, scraping, querying, alerting, and dashboard integration.",
  ],
  "threat_model_youtube": [
    "Threat modelling with STRIDE",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=OWASP+STRIDE+threat+modeling+DFD+tutorial",
    "Watch a current practical STRIDE and data-flow-diagram walkthrough before producing the Nexus threat model.",
  ],
  "owasp_threat": [
    "Threat Modeling Cheat Sheet",
    "Read",
    "OWASP",
    "https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html",
    "DFDs, trust boundaries, threat identification, risk treatment, and repeatable threat-model workflow.",
  ],
  "owasp_asvs": [
    "OWASP ASVS",
    "Reference",
    "OWASP",
    "https://owasp.org/www-project-application-security-verification-standard/",
    "Use the verification requirements as a measurable application-security completion checklist.",
  ],
  "secrets_manager": [
    "AWS Secrets Manager documentation",
    "Reference",
    "Amazon Web Services",
    "https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html",
    "Store, retrieve, rotate, audit, and control access to application and database secrets.",
  ],
  "devsecops_youtube": [
    "DevSecOps pipeline full course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=DevSecOps+pipeline+Semgrep+Trivy+Gitleaks+SBOM+GitHub+Actions",
    "See SAST, SCA, container, secret, SARIF, and SBOM gates combined in a practical CI/CD workflow.",
  ],
  "github_code_security": [
    "GitHub code security",
    "Read",
    "GitHub",
    "https://docs.github.com/en/code-security",
    "Code scanning, secret scanning, dependency review, SARIF uploads, and security policy.",
  ],
  "semgrep": [
    "Semgrep documentation",
    "Reference",
    "Semgrep",
    "https://semgrep.dev/docs/",
    "SAST rule configuration, CI integration, ignore policy, findings triage, and custom rules.",
  ],
  "trivy": [
    "Trivy documentation",
    "Reference",
    "Aqua Security",
    "https://trivy.dev/latest/docs/",
    "Container, filesystem, IaC, secret, SBOM, and vulnerability scanning.",
  ],
  "gitleaks": [
    "Gitleaks documentation",
    "Reference",
    "Gitleaks",
    "https://github.com/gitleaks/gitleaks",
    "Pre-commit and CI secret detection, custom rules, baselines, and allowlists.",
  ],
  "syft": [
    "Syft documentation",
    "Reference",
    "Anchore",
    "https://github.com/anchore/syft",
    "Generate SPDX and CycloneDX SBOMs for images and filesystems.",
  ],
} as const satisfies Record<string, NexusResourceTuple>;
