import type { NexusResourceTuple } from "./types";

export const foundationResources = {
  "cs50p": [
    "CS50’s Introduction to Programming with Python",
    "Course",
    "Harvard CS50",
    "https://cs50.harvard.edu/python/",
    "A rigorous video-led Python course with exercises, testing, file I/O, regex, OOP, and a final project.",
  ],
  "cs50p_youtube": [
    "CS50P full course on YouTube",
    "Watch",
    "Harvard CS50 / freeCodeCamp",
    "https://www.youtube.com/watch?v=nLRL_NcnK-4",
    "Watch the complete course when you need a guided walkthrough before implementing the Python engineering tasks.",
  ],
  "missing_semester": [
    "The Missing Semester of Your CS Education",
    "Course",
    "MIT",
    "https://missing.csail.mit.edu/2026/",
    "Shell, Git, debugging, profiling, command-line data tools, security, and developer workflow.",
  ],
  "python_packaging": [
    "Python Packaging User Guide",
    "Reference",
    "Python Packaging Authority",
    "https://packaging.python.org/en/latest/tutorials/packaging-projects/",
    "Current guidance for pyproject.toml, package layout, builds, dependencies, and distribution.",
  ],
  "pytest": [
    "pytest getting started",
    "Reference",
    "pytest",
    "https://docs.pytest.org/en/stable/getting-started.html",
    "Fixtures, parametrization, assertions, test discovery, and practical testing patterns.",
  ],
  "postgres_tutorial": [
    "PostgreSQL tutorial",
    "Read",
    "PostgreSQL",
    "https://www.postgresql.org/docs/current/tutorial.html",
    "Official SQL, schema, joins, aggregates, transactions, and database concepts.",
  ],
  "postgres_explain": [
    "Using EXPLAIN",
    "Reference",
    "PostgreSQL",
    "https://www.postgresql.org/docs/current/using-explain.html",
    "Read query plans correctly and prove that indexes improve the analytics lab.",
  ],
  "algorithms": [
    "Algorithms and data structures",
    "Practice",
    "VisuAlgo",
    "https://visualgo.net/en",
    "Interactive visualizations for heaps, graphs, BFS, DFS, shortest paths, and complexity.",
  ],
  "docker_get_started": [
    "Docker Get Started",
    "Course",
    "Docker",
    "https://docs.docker.com/get-started/",
    "Images, containers, volumes, networks, Compose, and multi-container application fundamentals.",
  ],
  "docker_youtube": [
    "Docker full course",
    "Watch",
    "TechWorld with Nana",
    "https://www.youtube.com/watch?v=3c-iBn73dDE",
    "A visual, practical walkthrough of containers, images, registries, Compose, and deployment workflow.",
  ],
  "nginx": [
    "NGINX beginner’s guide",
    "Reference",
    "NGINX",
    "https://nginx.org/en/docs/beginners_guide.html",
    "Configuration structure, reverse proxying, static content, and request routing.",
  ],
  "github_actions": [
    "GitHub Actions documentation",
    "Reference",
    "GitHub",
    "https://docs.github.com/en/actions",
    "Workflow syntax, caching, artifacts, environments, secrets, security hardening, and deployment.",
  ],
  "postgres_backup": [
    "PostgreSQL backup and restore",
    "Reference",
    "PostgreSQL",
    "https://www.postgresql.org/docs/current/backup.html",
    "Authoritative pg_dump, pg_restore, and recovery guidance for tested backups.",
  ],
  "fastapi": [
    "FastAPI Tutorial",
    "Course",
    "FastAPI",
    "https://fastapi.tiangolo.com/tutorial/",
    "The official recommended path through typed APIs, validation, dependencies, auth, tests, and deployment.",
  ],
  "fastapi_youtube": [
    "FastAPI comprehensive course",
    "Watch",
    "freeCodeCamp",
    "https://www.youtube.com/watch?v=0sOvCWFmrtA",
    "Long-form practical course covering FastAPI, PostgreSQL, authentication, testing, and deployment.",
  ],
  "sqlalchemy": [
    "SQLAlchemy Unified Tutorial",
    "Read",
    "SQLAlchemy",
    "https://docs.sqlalchemy.org/en/20/tutorial/",
    "ORM and Core patterns, sessions, transactions, relationships, and query construction.",
  ],
  "alembic": [
    "Alembic tutorial",
    "Reference",
    "Alembic",
    "https://alembic.sqlalchemy.org/en/latest/tutorial.html",
    "Database migration setup, revision generation, upgrade/downgrade flows, and production practices.",
  ],
  "pydantic": [
    "Pydantic documentation",
    "Reference",
    "Pydantic",
    "https://docs.pydantic.dev/latest/",
    "Typed validation models, settings, serialization, custom validators, and JSON Schema.",
  ],
  "openapi": [
    "OpenAPI Specification",
    "Reference",
    "OpenAPI Initiative",
    "https://spec.openapis.org/oas/latest.html",
    "Use when checking API contracts, schema quality, errors, pagination, and documentation.",
  ],
  "owasp_authn": [
    "Authentication Cheat Sheet",
    "Read",
    "OWASP",
    "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
    "Password storage, session handling, MFA, reauthentication, and secure authentication design.",
  ],
  "owasp_authz": [
    "Authorization Cheat Sheet",
    "Read",
    "OWASP",
    "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html",
    "Deny-by-default, least privilege, object-level checks, policy testing, and access-control design.",
  ],
  "jwt": [
    "JSON Web Token Cheat Sheet",
    "Reference",
    "OWASP",
    "https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html",
    "Token storage, signature validation, revocation, rotation, sidejacking, and common JWT failures.",
  ],
  "next_learn": [
    "Next.js Learn",
    "Course",
    "Next.js",
    "https://nextjs.org/learn",
    "Official hands-on learning path for App Router, data, authentication, accessibility, and deployment.",
  ],
  "next_docs": [
    "Next.js App Router documentation",
    "Reference",
    "Next.js",
    "https://nextjs.org/docs/app/getting-started",
    "Current reference for layouts, server/client components, route handlers, caching, errors, and deployment.",
  ],
  "next_youtube": [
    "Next.js App Router full course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=Next.js+App+Router+TypeScript+full+course+2026",
    "Use the current full-course results alongside the official documentation while building the operations dashboard.",
  ],
  "typescript": [
    "TypeScript Handbook",
    "Read",
    "Microsoft",
    "https://www.typescriptlang.org/docs/handbook/intro.html",
    "Types, narrowing, generics, modules, utility types, and strict application design.",
  ],
  "react": [
    "React Learn",
    "Read",
    "React",
    "https://react.dev/learn",
    "State, effects, forms, component composition, data flow, and modern React mental models.",
  ],
  "shadcn": [
    "shadcn/ui documentation",
    "Reference",
    "shadcn",
    "https://ui.shadcn.com/docs",
    "Accessible component patterns for forms, tables, dialogs, navigation, and dashboards.",
  ],
  "weasyprint": [
    "WeasyPrint first steps",
    "Reference",
    "WeasyPrint",
    "https://doc.courtbouillon.org/weasyprint/stable/first_steps.html",
    "HTML/CSS-to-PDF generation, page styling, fonts, and print-ready business documents.",
  ],
  "tech_writing": [
    "Technical Writing Courses",
    "Course",
    "Google for Developers",
    "https://developers.google.com/tech-writing",
    "Write clearer READMEs, architecture notes, case studies, procedures, and troubleshooting guides.",
  ],
  "mermaid": [
    "Mermaid documentation",
    "Reference",
    "Mermaid",
    "https://mermaid.js.org/intro/",
    "Create maintainable architecture, sequence, ERD, state, and flow diagrams in Markdown.",
  ],
  "de_zoomcamp": [
    "Data Engineering Zoomcamp",
    "Course",
    "DataTalks.Club",
    "https://github.com/DataTalksClub/data-engineering-zoomcamp",
    "Free project-driven course on pipelines, orchestration, warehouses, batch, streaming, and a capstone.",
  ],
  "de_youtube": [
    "Data Engineering Zoomcamp videos",
    "Watch",
    "DataTalks.Club",
    "https://www.youtube.com/results?search_query=DataTalksClub+Data+Engineering+Zoomcamp+2026",
    "Follow the lecture recordings while implementing ETL, orchestration, warehouses, and reporting.",
  ],
  "pandas": [
    "pandas user guide",
    "Reference",
    "pandas",
    "https://pandas.pydata.org/docs/user_guide/index.html",
    "Data ingestion, cleaning, missing data, joins, reshaping, groupby, and file formats.",
  ],
  "dimensional": [
    "Dimensional modelling guide",
    "Read",
    "dbt Labs",
    "https://docs.getdbt.com/terms/dimensional-modeling",
    "Facts, dimensions, grain, slowly changing dimensions, and analytics-friendly modelling.",
  ],
  "airflow": [
    "Apache Airflow tutorials",
    "Course",
    "Apache Airflow",
    "https://airflow.apache.org/docs/apache-airflow/stable/tutorial/index.html",
    "Official tutorials for DAGs, TaskFlow, scheduling, retries, testing, backfills, and operations.",
  ],
  "airflow_youtube": [
    "Apache Airflow course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=Apache+Airflow+3+full+course+2026",
    "Use a recent Airflow 3 course to see DAG authoring, scheduling, retries, logs, and Docker deployment end to end.",
  ],
  "r4ds": [
    "R for Data Science, 2nd edition",
    "Read",
    "Hadley Wickham and contributors",
    "https://r4ds.hadley.nz/",
    "Free practical book for data transformation, visualization, reporting, and reproducible analysis in R.",
  ],
} as const satisfies Record<string, NexusResourceTuple>;
