import type { NexusResourceTuple } from "./types";

export const systemsResources = {
  "github_profile": [
    "Managing your profile README",
    "Reference",
    "GitHub",
    "https://docs.github.com/en/account-and-profile/how-tos/profile-customization/managing-your-profile-readme",
    "Present projects, evidence, links, diagrams, and profile narrative clearly.",
  ],
  "system_design": [
    "System Design Primer",
    "Practice",
    "Donne Martin and contributors",
    "https://github.com/donnemartin/system-design-primer",
    "Open explanations, trade-offs, diagrams, interview prompts, and distributed-systems patterns.",
  ],
  "rust_youtube": [
    "Beginner’s Series to Rust",
    "Watch",
    "Microsoft Learn",
    "https://learn.microsoft.com/en-us/shows/beginners-series-to-rust/",
    "Video series introducing Rust fundamentals and the language features that matter for CLI tooling.",
  ],
  "rust_book": [
    "The Rust Programming Language",
    "Read",
    "Rust Project",
    "https://doc.rust-lang.org/book/",
    "The official Rust book covering ownership, lifetimes, traits, errors, tests, concurrency, and project structure.",
  ],
  "rust_cli": [
    "Command Line Applications in Rust",
    "Course",
    "Rust CLI Working Group",
    "https://rust-cli.github.io/book/",
    "Argument parsing, files, errors, testing, packaging, and practical CLI architecture.",
  ],
  "sarif": [
    "SARIF specification and guidance",
    "Reference",
    "OASIS / Microsoft",
    "https://sarifweb.azurewebsites.net/",
    "Understand valid static-analysis output before emitting SARIF into GitHub code scanning.",
  ],
  "spring_youtube": [
    "Spring Boot full course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=Spring+Boot+3+full+course+2026",
    "Use a current Spring Boot course for JPA, validation, testing, Docker, and enterprise service structure.",
  ],
  "spring": [
    "Building a RESTful Web Service",
    "Course",
    "Spring",
    "https://spring.io/guides/gs/rest-service",
    "Official Spring Boot guide for controllers, application structure, build tooling, and REST endpoints.",
  ],
  "spring_data": [
    "Spring Data JPA reference",
    "Reference",
    "Spring",
    "https://docs.spring.io/spring-data/jpa/reference/",
    "Repositories, transactions, query methods, locking, projections, and persistence patterns.",
  ],
  "beej_c": [
    "Beej’s Guide to C Programming",
    "Read",
    "Brian Hall",
    "https://beej.us/guide/bgc/",
    "Free practical C guide covering memory, pointers, structs, files, compilation, and systems fundamentals.",
  ],
  "learncpp": [
    "LearnCpp.com",
    "Course",
    "LearnCpp",
    "https://www.learncpp.com/",
    "Comprehensive modern C++ course covering language fundamentals, RAII, STL, classes, testing, and build practices.",
  ],
  "cmake": [
    "CMake tutorial",
    "Reference",
    "CMake",
    "https://cmake.org/cmake/help/latest/guide/tutorial/",
    "Official step-by-step guide for portable C/C++ project configuration and builds.",
  ],
  "kotlin_youtube": [
    "Kotlin Android development course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=Android+Kotlin+Jetpack+Compose+full+course+2026",
    "Watch a current Android/Kotlin course while implementing the offline requisition workflow.",
  ],
  "android": [
    "Android Basics with Compose",
    "Course",
    "Android Developers",
    "https://developer.android.com/courses/android-basics-compose/course",
    "Official Kotlin/Compose course for app architecture, state, navigation, persistence, and networking.",
  ],
  "csharp": [
    "Take your first steps with C#",
    "Course",
    "Microsoft Learn",
    "https://learn.microsoft.com/en-us/training/paths/get-started-c-sharp-part-1/",
    "Structured C# modules for types, collections, files, exceptions, LINQ, and application design.",
  ],
  "dotnet_youtube": [
    ".NET and C# full course",
    "Watch",
    "YouTube curated search",
    "https://www.youtube.com/results?search_query=.NET+9+C%23+full+course+2026",
    "Use a current .NET course for file processing, validation, tests, and packaging the Excel validator.",
  ],
  "laravel": [
    "Laravel Bootcamp",
    "Course",
    "Laravel",
    "https://bootcamp.laravel.com/",
    "Official guided build covering routes, validation, authentication, database records, and deployment concepts.",
  ],
} as const satisfies Record<string, NexusResourceTuple>;
