import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Metadata } from 'next'
import { ArrowLeft, CheckCircle2 } from 'lucide-react'
import { caseStudies } from '@/data/case-studies'
import { getProject } from '@/data/war-mode-projects'
export async function generateStaticParams() { return caseStudies.map((study) => ({ slug: study.slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const study = caseStudies.find((item) => item.slug === slug); return { title: study ? `${study.title} | Case Study` : 'Case Study', description: study?.summary ?? 'Technical case study.' } }
export default async function CaseStudyPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const study = caseStudies.find((item) => item.slug === slug); if (!study) notFound(); const project = getProject(study.projectSlug); return <main className="space-y-8 text-slate-100"><Link href="/case-studies" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-300"><ArrowLeft size={16}/> Back to case studies</Link><section className="rounded-[2rem] border border-slate-800 bg-[#070A0F] p-6 md:p-10"><p className="text-xs font-semibold uppercase tracking-[0.35em] text-sky-300">Case study</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] text-white md:text-6xl">{study.title}</h1><p className="mt-4 max-w-3xl text-base leading-8 text-slate-300">{study.subtitle}</p>{project && <div className="mt-6 flex flex-wrap gap-2">{project.stack.slice(0,10).map((tech)=><span key={tech} className="rounded-full bg-slate-900 px-3 py-1 text-xs text-slate-300">{tech}</span>)}</div>}</section><CaseBlock title="Problem" items={[study.problem]} /><CaseBlock title="Architecture" items={study.architecture} /><CaseBlock title="Key decisions" items={study.keyDecisions} /><CaseBlock title="Implementation" items={study.implementation} /><CaseBlock title="Quality gates" items={study.quality} /><CaseBlock title="Results" items={study.results} /><CaseBlock title="Future improvements" items={study.futureImprovements} /></main> }
function CaseBlock({ title, items }: { title: string; items: string[] }) { return <section className="rounded-3xl border border-slate-800 bg-slate-950/70 p-6"><h2 className="text-2xl font-bold text-white">{title}</h2><ul className="mt-4 space-y-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-7 text-slate-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-300"/><span>{item}</span></li>)}</ul></section> }
