// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim() || "";
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?.trim() ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() ||
  "";

export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY,
);

const createFallbackQueryBuilder = (table: string) => {
  const builder = {
    table,
    data: null,
    error: null,
    count: 0,
    select: () => builder,
    eq: () => builder,
    order: () => builder,
    limit: () => builder,
    single: async () => ({ data: null, error: null }),
    maybeSingle: async () => ({ data: null, error: null }),
    insert: async () => ({ data: null, error: null }),
    update: async () => ({ data: null, error: null }),
    delete: async () => ({ data: null, error: null }),
  };

  return builder;
};

const fallbackAuth = {
  getSession: async () => ({ data: { session: null }, error: null }),
  onAuthStateChange: () => ({
    data: {
      subscription: {
        unsubscribe: () => undefined,
      },
    },
    error: null,
  }),
  signInWithPassword: async () => ({
    data: { user: null, session: null },
    error: new Error("Supabase is not configured for sign-in."),
  }),
  signOut: async () => ({ error: null }),
};

const fallbackSupabase = {
  auth: fallbackAuth,
  from: (table: string) => createFallbackQueryBuilder(table),
  rpc: async () => ({ data: null, error: null }),
} as unknown as SupabaseClient;

// Import the supabase client like this:
// import { supabase } from '@/integrations/supabase/client'

export const supabase: SupabaseClient = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : fallbackSupabase;
